### ISSUE TITLE
Exclude inline data URI

### ISSUE THREAD

**Issue by attiks** [filamentgroup/criticalCSS#18]
We're using sass and we inline most of our background svg's using data URI's, but we need a way to exclude them before inlining the critical css. For the moment we run sed from inside our Gruntfile (sed -i  \'/data:/d\' css/critical.css), but it would be easier if it was handled by criticalCSS.

**Comment by jefflembeck** [comment]
We have a `forceInclude`, I think a `forceExclude` is a reasonable option.
