### ISSUE TITLE
Option to include @font-face and @keyframes blocks in critical css

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/criticalCSS#25]
Currently, critical css does not include `@font-face` or `@keyframes` declarations, but I think it at least optionally should be able to. 

We could do this in a simple way by including any of these we encounter, or the harder way by seeing if they're referenced at all by elements in the page that are deemed critical. The latter seems tough but maybe there's some CSSOM way to do that if desirable. I think the simple way would be fine for now, as an optional thing.

**Comment by stuntdawg** [comment]
is there any update on this? i'd love to see these added in somehow.

**Comment by scottjehl** [comment]
no update but I agree we should still do it. thanks for the bump

**Comment by johnbender** [comment]
PR for including all `@font-faces` https://github.com/filamentgroup/criticalCSS/pull/51
