### ISSUE TITLE
getRules returns rules lowercased

### ISSUE THREAD

**Issue by BradleyStaples** [filamentgroup/criticalCSS#32]
Our CSS uses camelCased selectors, but the stdout outputted from critical.js > getRules() returns all lowercased selectors, so the majority of our CSS fails to match in the window.document.querySelector() statement in criticalrunner.js.

I'm unsure if this is something from phantomJS or what else is the source cause of the issue at this point.

**Comment by BradleyStaples** [comment]
Thinking this is a phantomJS bug, although I'm not 100% sure. In case it is, I opened an issue over there as well. https://github.com/ariya/phantomjs/issues/13197

**Comment by malchata** [comment]
This is still going on in the CLI version as of 2016. Are there any plans to fix this?

**Comment by dracos** [comment]
Just been bitten by this, wondered for ages why my form (ID ending in "Form") had lost its critical style :)

**Comment by jeffwhelpley** [comment]
FYI to all here I just submitted a PR to fix this issue. The problem was that the DOM API to pull the styles will for some reason always be lower case unless you include the HTML5 doctype in the document:

```
<!DOCTYPE html>
<html>
  ...
</html>
```
