### ISSUE TITLE
Feature Request: allow passing config to or set configuration for phantomjs

### ISSUE THREAD

**Issue by bitinn** [filamentgroup/criticalCSS#33]
Does criticalCSS support local https using self-signed cert?

I get this error:

```
Error: PHANTOM ERROR: Error: Page didn't open: https://local.dev/
```

**Comment by bitinn** [comment]
Actually I would change my question to feature request:

allow passing custom config to phantomjs (through config.json or command), this allow us to change settings like `ignoreSslErrors`, which is needed to get my scenario working :)

**Comment by jefflembeck** [comment]
@bitinn - that's an A+ feature request. Lemme see what I can do about that when I can (it might be a few weeks, a bit stacked right now).

Thanks!

**Comment by bitinn** [comment]
@jefflembeck cheers!

Also a h/t on this issue, criticalCSS will probably encounter the same problem sooner or later:

https://github.com/pocketjoso/penthouse/issues/58
