### ISSUE TITLE
Implementation for dynamic websites

### ISSUE THREAD

**Issue by mattymess** [filamentgroup/criticalCSS#34]
This seems like it would work really well for pages that aren't changing very often. However, most of the web is dynamic where the header and footer might be the only things on the page that stay the same throughout the site. 

How do you address this use case?

**Comment by scottjehl** [comment]
Well, we typically run it on every unique template of a site. While the content within the pages that use that template can vary, the CSS that runs those pages is often stable (hence the unique template part). So... assuming the site is set up like that, that's how we typically use it.

Whenever the layout or template of a particular page changes, you'd need to re-run the task on that template to extract its critical styles. If you have a page that frequently uses different designs, you'd need to run the task whenever one of the new designs is deployed.

Hope that helps!

**Comment by mattymess** [comment]
Thanks for the reply. That makes perfect sense. 

I'm curious if you've tried using Google's PageSpeed module for handling inlining JS/CSS and if it works better/worse than something like criticalCSS?

**Comment by scottjehl** [comment]
I haven’t used it personally, no. But I think it does have a similar feature. Not sure how it’s handled

**Comment by mattymess** [comment]
Fair enough. Thanks again, Scott! 

P.S. Just bought your new book--really looking forward to diving in.

**Comment by scottjehl** [comment]
Thanks so much! I hope you find it useful :)
