### ISSUE TITLE
How to use this withiout grunt and gulp?

### ISSUE THREAD

**Issue by JulianeAlbuquerque** [filamentgroup/criticalCSS#36]
Hello, I don't know how to use this without grunt and gulp, Can you help me please?

**Comment by devrchancay** [comment]
you solved it ? @JulianeAlbuquerque

**Comment by mindgamesru** [comment]
It's pretty ease to use:

var criticalcss = require("criticalcss"); //install it via npm
var fs = require('fs'); //install it via npm

criticalcss.getRules('common/css/styles.css', function(err, output) {
        if (err) {
            throw new Error(err);
        } else {
            criticalcss.findCritical("https://www.site.com/", {rules: JSON.parse(output)}, function (err, output) {
                if (err) {
                    throw new Error(err);
                } else {
                    fs.writeFileSync('common/css/critical.css', output);
                }
            });
        }
    });

Profit! You got critical.css in common/css/ folder.

**Comment by lukehatfield** [comment]
I'm new to npm also, outside of gulp. Is this the kind of thing that you run `npm run` and then whatever you called the script in the package.json file?

**Comment by mindgamesru** [comment]
You can run it using scripts section in the package.json and then`npm run` or you can do it using gulp (as far as it's a task runner).
