### ISSUE TITLE
Using with a local non-signed SSL certificate

### ISSUE THREAD

**Issue by rtvenge** [filamentgroup/criticalCSS#38]
I see there is a way to suppress unsigned certs in [PhantomJS CLI](http://phantomjs.org/api/command-line.html), but is there a way to do this directly with CriticalCSS? My local setup has SSL enabled with a self-signed certificate and it would be nice to ignore these errors.

Thanks!

**Comment by S1SYPHOS** [comment]
I use wget to clone the page I want, using `--no-check-certificate` and then point `criticalCSS` to the generated HTML file ..
