### ISSUE TITLE
PhantomJS error

### ISSUE THREAD

**Issue by mikelinden1** [filamentgroup/criticalCSS#59]
When I run critical CSS using grunt (`grunt-criticalcss`) I get the following error. This was working up until recently and I know something happened with PhantomJS recently. Anything I can do?

Running "criticalcss:post" (criticalcss) task

Something went wrong with phantomjs...
Fatal error: PHANTOM ERROR: ReferenceError: Can't find variable: osdlfm
TRACE:
 -> http://localhost/skift/2018/01/03/upscale-destinations-and-tech-innovations-to-watch-in-2018-new-luxury/: 1 (in function global code)
 -> undefined: 0 (in function exit)
 -> phantomjs://code/criticalrunner.js: 100
 -> phantomjs://platform/webpage.js: 286 (in function _onPageOpenFinished)PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

**Comment by rickydazla** [comment]
[NPM is out of date](https://github.com/filamentgroup/criticalCSS/issues/64)
