### ISSUE TITLE
NPM: Publish recent dependency changes (re: PhantomJS => Headless Chrome)

### ISSUE THREAD

**Issue by rickydazla** [filamentgroup/criticalCSS#64]
[NPM repo](https://www.npmjs.com/package/criticalcss) was last published 2 years ago but there was a recent merge commit to this repo that updated the script to use Headless Chrome instead of PhantomJS... Any chance someone could publish [those changes](https://github.com/filamentgroup/criticalCSS/pull/62) to NPM?

**Comment by notiv-nt** [comment]
I got an error:

```
Can't find variable: Promise
```

Issue + 1
Phantomjs -1
